# Domain_Names
wordList = ['meantime', 'upcoming', 'newsroom', 'courthouse', 'headline', 'carefree', 'taproot', 'household', 
'bookmobile', 'watchdog', 'foothill', 'bankroll', 'jetliner', 'however', 'caveman', 'newsreel', 
'wasteland', 'lukewarm', 'underfoot', 'foreclose', 'dishcloth', 'footnote', 'cardstock', 
'turnaround', 'carryall', 'foreword', 'downunder', 'tenfold', 'textbook', 'upend', 'afterimage', 
'diskdrive', 'carload', 'northeast', 'glassmaking', 'horsepower', 'grandchild', 'anyway', 'handgun', 
'teaspoon', 'forklift', 'whatsoever', 'centercut', 'setback', 'oneself', 'commonwealth', 'grandmaster', 
'upstairs', 'dishwater', 'grandmother', 'granduncle', 'butterfingers', 'keystroke', 'upperclassman', 
'foreshadow', 'repairman', 'sunflower', 'duckpin', 'tabletop', 'tableware', 'afterglow', 'highland', 
'sheepskin', 'sheepskin', 'spokesperson', 'grandchildren', 'weekday', 'courtyard', 'baseball', 
'grandfather', 'whitefish', 'gumball', 'update', 'undercut', 'handmade', 'comeback', 'supermen', 
'forebrain', 'foresee', 'sweetmeat', 'butterflies', 'uptime', 'snowbird', 'toolbox', 'passbook', 
'newsman', 'walkways', 'highball', 'upbeat', 'someone', 'onetime', 'boardwalk', 'fishhook', 
'telltale', 'daisywheel', 'nevermore', 'waterpower', 'bypass', 'eyelid', 'grandparent', 'warfare', 
'showplace', 'widespread', 'sharpshooter', 'daydream', 'upstanding', 'cardsharp', 'backdrop', 
'teammate', 'foreground', 'bookshelf', 'sideburns', 'wastepaper', 'talebearer', 'tailspin', 'wavelike', 
'standout', 'sharecropper', 'backstroke', 'driveway', 'softball', 'headquarters', 'superweapon', 
'limelight', 'timesaving', 'honeysuckle', 'atchcase', 'underbelly', 'daybook', 'turntable', 
'wastebasket', 'tagalong', 'housework', 'uppercase', 'anymore', 'forefinger', 'hookup', 'carfare', 
'supersensitive', 'bellboy', 'itself', 'superstar', 'goodbye', 'horsefly', 'pinhole', 'washout', 
'tailpiece', 'backbone', 'stronghold', 'blueprint', 'bookmark', 'spacewalk', 'railroad', 'carhop', 
'tablecloth', 'mothball', 'rattletrap', 'fishhook', 'tabletop', 'allover', 'shipbottom', 'tailcoat', 
'sandlot', 'wastewater', 'matchbox', 'snowbird', 'watchman', 'himself', 'anywhere', 'duckweed', 
'daisywheel', 'throwback', 'uptake', 'eyesight', 'teacup', 'comedown', 'fruitcup', 'bluebird', 
'taskmaster', 'sunfish', 'bankbook', 'taproot', 'upstroke', 'uproot', 'footlocker', 'bugspray', 
'upside', 'something', 'tabletop', 'forever', 'sunroof', 'sweetheart', 'whatever', 'touchdown', 
'shoemaker', 'newsstand', 'bootstrap', 'newsworthy', 'nowhere', 'wayfarer', 'watchtower', 'carpetbagger', 
'crossbreed', 'cancan', 'spearmint', 'wheelhouse', 'waterwheel', 'herein', 'forearm', 'rattlesnake', 
'turnbuckle', 'friendship', 'grassland', 'backtrack', 'turnbuckle', 'airport', 'timeshare', 'fireproof', 
'sharecropper', 'turnoff', 'taleteller', 'turnabout', 
'basketball', 'taillike', 'standoff', 'motherhood', 'alongside', 'underbid', 'superscript', 'turnaround', 
'superhero', 'fisherman', 'target', 'overboard', 'waterproof', 'telltale', 'comeback', 'blackboard', 
'backspin', 'tenfold', 'timeshare', 'upward', 'lifelong', 'warpath', 
'anyone', 'crosswalk', 'taillight', 'dishpan', 'backache', 'sixfold', 'newsprint', 'cannot', 'candlelight', 
'watchmaker', 'moonlit', 'headlight', 'uphill', 'washroom', 
'uplink', 'anyplace', 'horsehair', 'newsboy', 'upshot', 'fireflies', 'coffeemaker', 'fireball', 'popcorn', 
'footrest', 'woodshop', 'newsperson', 'cabdriver', 'sisterhood', 'turncoat', 'watercooler', 'washrag', 
'silversmith', 'background', 'ashtray', 'carport', 'noisemaker', 'standpoint', 'stonewall', 'underground', 
'jumpshot', 'keynote', 'showoff', 'crewcut', 'dogwood', 'schoolboy', 'wardroom', 'nutcracker', 'forefather', 
'grandstand', 'weekend', 'keypunch', 'allspice', 'intake', 'saucepan', 'uppermost', 'backbite', 'taillight', 
'sundown', 'snowbank', 'grandaunt', 'therefore', 'paycheck', 'tenderfoot', 'meanwhile', 'someday', 'pinup', 
'uptown', 'brainchild', 'takeout', 'grandnephew', 'bedclothes', 'eardrop', 'supercool', 'racquetball', 
'notebook', 'backward', 'backspace', 'lifetime', 'foresight', 
'elsewhere', 'rainbow', 'carsick', 'watermelon', 'superfine', 
'earthquake', 'uppercut', 'fishbowl', 'waybill', 'hometown', 
'dairymaid', 'careworn', 'drawbridge', 'teamwork', 'pickup', 'stoplight', 'stagehand', 
'salesclerk', 'keystone', 'taillight', 'upgrade', 'egghead', 'homemade', 'daylight', 'motorcycle', 
'snowball', 'crossover', 'houseboat', 'washboard', 'longhouse', 'underact', 'underarm', 'pinwheel', 
'somebody', 'sidekick', 'commonplace', 'watchword', 'taillike', 'lifeline', 'also', 'backlog', 'ironwork', 
'sandlot', 'passport', 'playthings', 'spacewalk', 'overflow', 'washbowl', 'lifeguard', 'without', 
'railway', 'turnkey', 'slowdown', 'sundial', 'headache', 'blacklist', 'jellybean', 'takeoff', 
'bookseller', 'sunglasses', 'wavelength', 'forefoot', 'watermark', 'cornmeal', 'waterfall', 
'overabundance', 'bluebell', 'backfire', 'cargo', 'firebreak', 'honeybee', 'supernatural', 
'newscaster', 'playhouse', 'forewarn', 'schoolbook', 'bellhop', 'newfound', 'moonshine', 
'fishmonger', 'honeymoon', 'handbook', 'moonbeam', 'supercharge', 'daybreak', 'bedroom', 
'become', 'newsprint', 'fortnight', 'snowdrift', 'bodyguard', 'moonwalk', 'hereby', 'eggshell', 
'whitecap', 'doorstop', 'tablespoon', 'together', 'spillway', 'airplane', 'firewater', 'forebear', 
'superego', 'turnaround', 'fishbowl', 'fireboat', 'tenderfoot', 'thunderbird', 'schoolwork', 
'skyscraper', 'backhand', 'shortbread', 'stockroom', 'airline', 'underdog', 'afternoon', 'waterspout', 
'rainwater', 'carpool', 'someplace', 'today', 'watertight', 'earthworm', 'warehouse', 'scapegoat', 
'fishbowl', 'earthward', 'became', 'somehow', 'superstrong', 'wayside', 'taillike', 'takeoff', 'hereupon', 
'forego', 'standpipe', 'comeback', 'newsprint', 'newsletter', 
'forefeet', 'stagehand', 'newsdealer', 'sunlit', 'brainwash', 
'supersonic', 'catwalk', 'overcoat', 'wipeout', 'airlift', 'somewhat', 
'teaspoon', 'teenager', 'keypad', 'grandson', 'tailgate', 'anybody', 'graveyard', 'newsbreak', 
'underachieve', 'babysitter', 'inside', 
'fishtail', 'foregone', 'upthrust', 'thunderstorm', 'snowbird', 'schoolbus', 
'airmen', 'waterline', 'bluefish', 
'takeout', 'daybed', 'spacewalk', 'bedroll', 'upstate', 'teaspoon', 'upland']
# Protocols
ttp_ttps = ["http://", "https://"]
# Domain_Extensions
top_level_domain = [".com", ".net", ".org"]
times = [0.5, 0.4, 0.3, 0.2, 0.1, 1, 2, 3]


        
